---
title: "E Division Scores"
---



```{r}
#| include: false

# | results: hide
# | message: false
# | error: false
# | warning: false


library("tidyverse")
library("tinytable")
library("readxl")

library("DT")

# Read scores data

# library("googlesheets4")
# googlesheets4::gs4_auth()
# scores <- read_sheet("https://docs.google.com/spreadsheets/d/16LFFxrTdfarSuJUx-eCk9385awKteJzOA4CBg3WmLmE/edit?usp=drive_link")

scores <- read_excel( path="../../data/scores.xlsx")

scores <- scores |> 
  mutate(
    at = " at "
  ) |> 
  dplyr::select( WEEK, DATE, TIME, AWAY, AS, at, HS, HOME )

idx_evn <- which( scores$WEEK %% 2 == 0 )
idx_odd  <- which( scores$WEEK %% 2 == 1 )
idx_off  <- which( is.na(scores$WEEK) )


```




```{r}
#| warning: false



# scores |> 
#   # tt( theme="striped" ) |> 
#   tt() |> 
#   style_tt( i=0, background="skyblue3" ) |> 
#   style_tt( i=idx_off, background="white", color="grey20" ) |> 
#   style_tt( i=idx_odd, background="white", color="grey20" ) |> 
#   style_tt( i=idx_evn, background="grey90", color="grey20" ) |> 
#   style_tt( j=c(1,2,3,5,6,7), align="c" ) |> 
#   theme_html( portable=TRUE )

datatable( scores, options = list(
       pageLength = -1,
      initComplete = JS(
        "function(settings, json) {",
        "$(this.api().table().header()).css({'background-color': 'rgba(73, 172, 204)', 'color': 'white'});",
        "}")
    ))


```


