---
title: "League"
---


If you are new to New Mexico and looking to continue to play hockey or you have never played the game before, we have something that will fit your skill level and experience. We take inquires from new players all season long.

Due to the limited number of roster spots per team, new players typically enter the league as a substitute first. This allows us to evaluate each player and determine which division is the best fit and affords new players the ability to see if the league is a good fit for them. Furthermore, new players are encouraged to reach out as early in the season as possible so we have ample substitution opportunities before the playoffs and before the new season starts. New players that have been subbing are given priority over those that first reach out during new season sign-ups.

Please read through the information below, as well as the History , the Rules , Season Details , and New Player Sign-up.

League Format: 

NMHockey currently has programs at two different rinks in New Mexico: The Outpost Ice Arena in Albuquerque and The MAC in Rio Rancho. The league at the Outpost Ice Arena consists of 5 different level divisions with 4 teams in each: E division (Novice), D division, C division, B2 division, and B1 division. The MAC consists of 2 different level divisions with 4 teams in each: Intermediate and an Intermediate – Advanced. All games are sanctioned by USA Hockey and all players must be registered with USA Hockey to participate as a rostered player or substitute.

- Each team consists of 10-11 skaters and a goalie.
- Substitute players are provided (for a fee) for players unable to make their game.
- New captains are selected at the beginning of each season
- Team rosters are redrafted at the beginning of each season. Rosters and schedule are then announced at our kickoff parties or via the website.
- Each game has 2 USA Hockey sanctioned referees plus a scorekeeper/announcer.

Season Format:

- See Season Details for divisional game days and times.
- A season consists of a regular season and a post-season with playoffs and championship/consolation.
- Every player gets the same number of games regardless of regular and post-season standings.

Game Format:

- Games are 1-hr 15-min in length.
- (3) 20-min runtime periods.
- 5-min warm up and 1-min breaks between periods.
- 5-min 3 vs. 3 OT period for tied games after regulation.
- 3 vs. 3 shootouts period for games tied after OT.

Equipment:

Required:

- Skates (of course)
- Stick
- Shin Guards
- Socks
- Cup or Pelvic Protector
- Breezers (Pants)
- Elbow Pads
- Gloves
- Helmet

The following equipment is not required, but is HIGHLY recommended:

- Chest/Shoulder Protection
- Mouth Guard

Extras:

- Championship Cup – “Norskie Cup”
- Sportsmanship Award
- Discounted, high-quality league jerseys for rostered players
- Jersey Patches for player anniversaries and championships
- NMHockey.com features league standings, stats, schedule, photos and more.
- NMHockey occasionally hosts social events during the seasons, such as team unveiling parties, Halloween party, etc…




