---
title: "New or Returning Player Information"
---


If you have made it this far, hopefully you are interested in joining NMHockey. Below is the information on how to start getting on the ice. Please read through information on the League , the History , the Rules  and  Season Details  if you have not already done so.

Provide your information: Please send Joe Hanson an email at jhanson@nmhockey with the following information:

- Name
- Phone Number
- A brief description of your playing experience
- Which rink, Outpost, MAC or both, you are interested in skating at
- Are you interested in subbing and/or rostering to a team
- What night(s) you can play
- USA Hockey Registration – This can be done online at www.usahockey.com (Forward the email USAH emails you to jhanson@nmhockey.com )

We will return your email as soon as we can and let you know you are on the list for subbing and/or waiting for a roster spot on a team.

How we roster players for each new season: Each of the NMHockey divisions consist of 4 teams. We roster 10 to 11 skaters and 1 goalie on each team in order to optimize each player’s icetime. This means there is a limited number of roster spots on each team, as well as within each division itself. Due to the number of players needed and limited “good” icetime (i.e. before 11PM), expanding any given division is not an option at this time.
Priority is given to currently rostered players for one week once sign ups begin. Once we determine in what divisions and how many roster spots we have open, we use the following hierarchy to coarsely determine which players to roster:

- Players that had the previous season cut short by injury or another emergency.
- Players that have been subbing regularly and have been rostered in the league within the past two seasons.
- Players that have been subbing regularly.
- All other players.

It may appear that it is difficult for players in that last group to get rostered, but we have a pretty good track record of getting most players on a team.

We put a lot of effort into maintaining the parity of skill level in each division, while also trying to accommodate player’s personal schedules, development and other special requests. In order to accomplish this, we must consider many factors when choosing which players to sign up to any division, such as:

- Which players have indicated they want a roster spot versus only subbing.
- How we maintain 4 teams worth of skaters in each division.
- Are there players the Vice-Commissioners recommend moving up or down a division?
- Does the player’s skill level fit well within the band of a division’s skill range?
- Has a player shown positive behavior on the ice when they played?
- Has a player been subbing regularly and trying to get into the league for a while, but we have not been able to get them in?
- Has a player shown reliability in completing the seasons they signed up for, emergencies withstanding?
- Has a player subbed in the league enough times that we know their skill level?
- Has a player already submitted their USAH registration?
- Is a player in good financial standing with the league? i.e. has paid their sub fees, pay league fees on time, etc…

Once we have determined which players we feel are the best fit for the available roster spots, we will invite them to sign up.

As you can appreciate, based on all this, there are a lot of moving pieces, but it is our priority to ensure we provide a great playing experience for everyone involved.

How to Sign up if you already have the league jerseys: Players that are invited to join that have the league jerseys need only make a payment and submit their USA Hockey registration via email. Payments can be made through Venmo or check by mail. See Payment Methods for mailing address.

How to Sign up if you need to get the league jerseys: Once new players are signed up, we will provide information via email on how to purchase the jerseys.




