---
title: "Staff Responsibilities"
---




## Commissioners

- To be filled.


## Vice Commissioners

- Assist the commissioner in identifying the best candidates when openings to roster arise.
- Collect USA Hockey details for their division when the annual renewal comes around.
- Identify captains for each season.
- Arrange for substitute players throughout the season.
- Follow up on the sub list to ensure players have paid the subbing fee.
- Mediate disputes or complaints from captains, involving the commissioner as needed.
- Determine the final rankings for each player based on ratings by outgoing and incoming captains.
- Arrange and conduct the draft.


## Captains


Administrative

- Rank all players and substitutes prior to the draft. 
  - This is done both as an "incoming" and "outgoing" captain. That is, you rank the players for the season you will captain, and also for the season afterwards.
  - This is important. The vice commissioner will use these rankings to help determine suitable substitutes.
- Draft a team.
- In general, the captains are representatives or ambassadors for the league. With that, just try to make sure you’re being a bit more responsible, level-headed.


Weekly

- Get the roll call (usually though group text thread) each week and let the vice commissioner know with sufficient notice.
- Assign or determine an order for beverage duties. Try to identify if there are folks who don't drink, and either skip them or ask people to bring some Gatorade as well.


Games

- Final say on lines.

- Be nice to the refs. The league has worked pretty hard over the years to develop a good rapport. If we piss off the refs, then refs aren’t going to want to ref for B1.
- Try to clamp down if your team is getting a bit too hostile to the refs. There’s always some griping, but just make sure it stays minor.

- Please wear the captain "C".
  - Refs need to know who is “in charge”. Like if a timeout gets called by one person, and someone else says no.
  - Some of you might have them already from others, try to take care of them / not lose them, they’re not necessarily cheap to replace.

- Captains timeout
  - If teams are getting a bit overheated/chippy, captains can call a captains timeout to try to let some tempers cool down.
  - It doesn’t count towards either team’s timeout. The refs know about it.
  - Not needed too often, but it’s there in case it comes up.












